# Generated by Django 2.0.7 on 2018-07-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('headquarters', models.CharField(max_length=30)),
                ('founded', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('defunct', 'Defunct'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('industry', models.CharField(max_length=30)),
                ('number_employees', models.IntegerField()),
                ('founder', models.CharField(max_length=30)),
                ('products', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Developers',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('initial_release', models.CharField(max_length=30)),
                ('stable_release', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Developer')),
            ],
            options={
                'db_table': 'Engines',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('series', models.CharField(max_length=30)),
                ('release', models.DateField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Developer')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Engine')),
            ],
            options={
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('release_date', models.DateField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Developer')),
            ],
            options={
                'db_table': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('headquarters', models.CharField(max_length=30)),
                ('founded', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('defunct', 'Defunct'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('revenue', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Supported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Platform')),
            ],
            options={
                'db_table': 'Suported',
            },
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'website')},
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(through='api.Supported', to='api.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='developer',
            unique_together={('name', 'website')},
        ),
        migrations.AlterUniqueTogether(
            name='supported',
            unique_together={('game', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('name', 'website')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='engine',
            unique_together={('name', 'website')},
        ),
    ]
