# Generated by Django 2.0.7 on 2018-07-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release',
            new_name='release_date',
        ),
    ]
