# Generated by Django 2.0.7 on 2018-07-30 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_game_release_to_release_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='platform',
            name='developer',
        ),
        migrations.AlterUniqueTogether(
            name='supported',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supported',
            name='game',
        ),
        migrations.RemoveField(
            model_name='supported',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Supported',
        ),
    ]
