# Generated by Django 2.0.7 on 2018-07-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_platform_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.CharField(max_length=50),
        ),
    ]
