TESTDATA = {
        'name': 'test',
        'website': 'test.com',
        'headquarters': 'test',
        'founder': 'test',
        'founded': '2018-07-30',
        'release_date': '2018-07-30',
        'initial_release': 'test',
        'stable_release': 'test stable',
        'status': 'Unkown',
        'industry': 'test',
        'products': 'test',
        'number_employees': 100,
        'revenue': 1,
        'description': 'test description',
        'genre': 'test genre',
        'series': 'test series',
        'platforms': 'test, test ,test',
}
